SampleRailsApp/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello' => 'say#hello'
  get 'say/greet' => 'say#greet'
  get '/photo/:id' => 'say#photo', as: 'get_photo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SampleRailsApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

SampleRailsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

SampleRailsApp/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end

  def greet
    @name = params[:name]
  end

  def photo
    @id = params[:id]
    @sample_json = {name: 'Abhi', last_name: 'Ghosh', id: @id}
    # respond_to.as_json { @sample_json }
    respond_to do |format|
      format.json { render json: @sample_json }
      format.html
    end
  end
end

SampleRailsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

SampleRailsApp/app/helpers/say_helper.rb
module SayHelper
end

SampleRailsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

SampleRailsApp/app/views/say/greet.html.erb
<div class="some-class">
  Hello, <%= @name %>!
  <br>
  <%= link_to 'Check this out', get_photo_path(2), class: 'anchor_class' %>
</div>

SampleRailsApp/app/views/say/hello.html.erb
<div class="fun-times">
  <p>
    Date: <%= Time.now.mon() %>/<%= Time.now.day()  %>/<%= Time.now.year %>
  </p>
  <p>
    Time: <%= Time.now %>
  </p>
  <p class="author">
    &copy;Abhishek Ghosh 👨🏻‍💻
  </p>
</div>

SampleRailsApp/app/views/say/photo.html.erb
<div>
  <p>
    You are viewing photo with Id : <%= @id %>
  </p>
</div>